# Generated by Django 2.2.4 on 2019-08-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('Agua', 'Agua'), ('Fuego', 'Fuego'), ('Planta', 'Planta')], max_length=10),
        ),
    ]
